### ISSUE TITLE
issure while settingup minaccountage

### ISSUE THREAD

**Issue by madxtreme7018** [Darkempire78/Raid-Protect-Discord-Bot#3]
Hello, i have a issure output in the console if i want to setup the minimum accountage. i tried many combinations i also tried only one number and above 24h but all stuff not worked. however here is the output and hopefully someone can help me out:

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Darkempire78** [comment]
Hey,
You have to follow this template : "minAccountDate": justANumber (ex : "minAccountDate": 86400), 86400 is the number of the seconds in 24 hours. If it's not the issue, please send me a screenshot of the line.

**Comment by Darkempire78** [comment]
You can also contact me on Discord : Darkempire#8245

**Comment by nmaljkovich** [comment]
I encountered the same issue with the _minAccountAge_ cog, the parameter fails to set and the config file is cleared out (goodbye token key).
It's an easy fix, on **line 31** replace:
                
` data = json.dumps(data, indent=4, ensure_ascii=False)` 
with  
 ` newdata = json.dumps(data, indent=4, ensure_ascii=False)`

Because as it is, **line 34** is overwriting the config file with an unassigned variable:
`config.write(newdata)`

**Comment by Darkempire78** [comment]
Thanks you nmaljkovich, you are right.
I have push the new version

**Comment by FeelsBadMan1** [comment]
Thanks for the help and well i went inactive somehow
